name: "Hello world"

on: 
  push:
    branches:
      - ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    step:
      run: echo "Hacemos un pull del codigo"
      run: echo "Correr migraciones"
      run: echo "Generar binario"
      run: echo "Publicar version"
    